const SET_NOTIFICATION = "SET_NOTIFICATION";
const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION";
const REGISTER_SUCCESS = "REGISTER_SUCCESS";
const REGISTER_FAIL = "REGISTER_FAIL";
const USER_LOADED = "USER_LOADED";
const AUTH_TOKEN_ERROR = "AUTH_TOKEN_ERROR";

export {
  SET_NOTIFICATION, REMOVE_NOTIFICATION,
  REGISTER_SUCCESS, REGISTER_FAIL,
  USER_LOADED, AUTH_TOKEN_ERROR
};
