const SET_NOTIFICATION = "SET_NOTIFICATION";
const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION";

const REGISTER_SUCCESS = "REGISTER_SUCCESS";
const REGISTER_FAIL = "REGISTER_FAIL";
const USER_LOADED = "USER_LOADED";
const AUTH_TOKEN_ERROR = "AUTH_TOKEN_ERROR";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAIL = "LOGIN_FAIL";
const LOGOUT = "LOGOUT";

const SET_INVALID_ENTRIES = "SET_INVALID_ENTRIES";
const SET_VALID_ENTRIES = "SET_VALID_ENTRIES";
const CLEAR_ENTRIES_FEEDBACK = "CLEAR_ENTRIES_FEEDBACK";

const GET_PROFILE = "GET_PROFILE";
const GET_PROFILES = "GET_PROFILES";
const CREATE_PROFILE = "CREATE_PROFILE";
const UPDATE_PROFILE = "UPDATE_PROFILE";
const PROFILE_ERROR = "PROFILE_ERROR";
const CLEAR_PROFILE = "CLEAR_PROFILE";
const DELETE_ACCOUNT = "DELETE_ACCOUNT";
const GET_REPOS = "GET_REPOS";

const POSTS_GET = "POSTS_GET";
const POST_GET = "POST_GET";
const POST_ADD = "POST_ADD";
const POST_ERROR = "POST_ERROR";
const POST_DELETE = "POST_DELETE";
const COMMENT_ADD = "COMMENT_ADD";
const COMMENT_REMOVE = "COMMENT_REMOVE";
const UPDATE_LIKE = "UPDATE_LIKE";

export {
  SET_INVALID_ENTRIES, SET_VALID_ENTRIES, CLEAR_ENTRIES_FEEDBACK,
  SET_NOTIFICATION, REMOVE_NOTIFICATION, REGISTER_SUCCESS, REGISTER_FAIL,
  USER_LOADED, AUTH_TOKEN_ERROR, LOGIN_SUCCESS, LOGIN_FAIL, LOGOUT,
  GET_PROFILE, GET_PROFILES, CREATE_PROFILE, UPDATE_PROFILE,
  DELETE_ACCOUNT, PROFILE_ERROR, CLEAR_PROFILE, GET_REPOS,
  POSTS_GET, POST_GET, POST_ADD, POST_ERROR, POST_DELETE,
  COMMENT_ADD, COMMENT_REMOVE, UPDATE_LIKE
};
